{% set version = "1.3.2" %}

package:
  name: django-filer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-filer/django-filer-{{ version }}.tar.gz
  sha256: 192b8039d167d1fc71423f65dd0d9b67a296f4336a942dba95bcadc1fb734d81

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8,<1.11.999
    - easy-thumbnails >=2,<2.5
    - django-mptt >=0.6,<0.9
    - django_polymorphic >=0.7,<1.4
    - unidecode >=0.04,<0.05

test:
  imports:
    - filer
about:
  home: https://github.com/divio/django-filer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'File and Image Management Application for django'
  description: 
    A file management application for django that makes handling of files and images a breeze.
  doc_url: https://django-filer.readthedocs.io/
  dev_url: https://github.com/divio/django-filer

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
