travis:
  secure:
    BINSTAR_TOKEN: IqJHmFuHAbtH2pvaFNpcO11QYNwFeSdaiIHLK66RzDsl/h9F1Szxla7p8lsPJpmr9AH8xhxkT70kulaGbbW2KnS5WACsnEInCPx/GFMiu3KOKLcF8ZVgc/hyk6sK0sudMuycGNtGM6Aarj2x53OQG5bOtW4IEdQdlFfIkLz/pzi8gM2qQJCwYEHNoUI4hBn4utgOjd82OMQtouzvAMCnOGuew3oGGUWM963wSdo8YBEXoJ9WQecYhuwvoL6obS4sypgmvSPIPWFdI1mUUAfCovsrwtuT47VFC60oU0ML67BUN4yAtw/zKUP/3L03utFcvlqCibrpsOVTkploXk/Y4W1Z/lOE8rPK0kCb5SwgW0Xp8ie5xZYSCpc/gAoOOviokBMexFa7yYMcd+eHq6vDz1GNZ3wBU6USk6eH13ImYSe+SE9c6NVDEze5BhQrIExtN20wpr4MpqU0PZJOJqTZyjTMk/+xKM6AtQXQzL8mIP6YPVu2duoxxI94Xbuhv1jRjhEHVt+cSkt0pqWQiu9y0yLW3GJoA81Rn5ioC6E08KGENNr7u5qZ62/5NMVjHZX/qTwGHolny757IWE2tVbJJK1HTyeTRbzlg4P+YFvzMLSE869zH7FfYGngLk4k+l8rmHnBceFsVvW6H2/l6oGeCSKKjC+3GX4GVy0kJzv8Pf8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
