travis:
  secure:
    BINSTAR_TOKEN: dvcwbgPA6DBmCPcFH0wsF4PWLAMmcg6f7Y0vQLvpz6Pbt7rUM/lF/0f1pF5ZIueEpXRlJqTGWg5M7zmkSt1AAc9wWwKW8WVLAR0xGXXtOzW2cNuwSqFSn+QWMBj4mOlqiQAHS1ESXfcDdXKCd6+JaJ7ZJN6qpaIST8EVgdDY+ycnnpJ9nrrPKRfb/xZR8mzWfIK9jS4dHmfc/IrP+XxYSWGb4jtvpT7UaGS18EZrGX9oMZnE+Ral8ohJS/dqHTxpl7NQietCy3KuVkkKPMm0eGJl5nryB9QUM8ekYXedCTHvSu4mOYGgpckyHNQyvR/ujTIDubSdoQYrR+lBKshSt+DmByNeeVM37uX5tLJdZh8lH7Gj5pHzioiY17xG29atnQ2f/9u/w8pk3g65MfYGSpJMn/Xo6np3GYeQld6dRJXkLeccVAEwqUflN82TzO3vWghjc+xSsZDfssY9YYeOVqeGWhwefwAnAQdJkj05K+qV1zaasOXZ7Mk5dMFB5c4MrV+IIeHo7P2m5HiYpQL0mReQFDxYMiEZKmq3kUHuc4OQ1sVEqZCVWf9kbj1aighWjeiMFcq2ZrvKk2mNnX62uBj7NfMGwIQclJPy+yfcFUCeqEQr5Cu2u5IKRIK52MjJ3kTgVwTY9mG2kQYaYDrrYxXFD4iXAlP3ErdoEtuQNrw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
